global:
   scrape_interval: 10s
   scrape_timeout: 3s
   
scrape_configs:
   - job_name: "pawsandhearts-scrape"
     metrics_path: "/metrics"
     static_configs:
        - targets: ["host.docker.internal:5222"]
          labels:
            instance: "paws-and-hearts"
        - targets: ["host.docker.internal:5081"]
          labels:
            instance: "paws-and-hearts-file-service"